version: "3"
services:
  chrome:
    container_name: chrome
    image: selenium/standalone-chrome:4.1.3-20220327
    ports:
    - 4444:4444
    networks:
      - chromenet
  app:
    container_name: app
    image: jupyter/datascience-notebook
    user: root
    volumes:
      - ../:/home/jovyan/
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8888:8888
    networks:
      - chromenet
    restart: unless-stopped
    shm_size: 2gb
    tty: true
    privileged: true
    stdin_open: true
    command: jupyter notebook --port 8888 --NotebookApp.token='' --ip=0.0.0.0 --allow-root 
    depends_on: 
    - chrome
    environment:
      SELENIUM_URL: http://chrome:4444/wd/hub

networks: 
  chromenet: